# Reference: https://getfoundry.sh/guides/foundry-in-docker
services:
  # Foundry development container for the backend contracts
  foundry:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: foundry
    working_dir: /contracts
    volumes:
      - ./contracts:/contracts
    command: /bin/bash
    stdin_open: true
    tty: true

  # Local blockchain for testing
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: nft-story-anvil
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0
    profiles:
      - anvil
