name: NFT Story CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Check Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker services
        run: docker compose build foundry

      - name: Set up permissions for Docker
        run: |
          sudo chown -R 1000:1000 contracts || true
          mkdir -p contracts/out contracts/cache contracts/lib

      - name: Check versions
        run: DOCKER_USER="1000:1000" make version

      - name: Check formatting
        run: DOCKER_USER="1000:1000" make fmt-check

      - name: Build projects
        run: DOCKER_USER="1000:1000" make build

      - name: Run tests
        run: DOCKER_USER="1000:1000" make test
